### ISSUE TITLE
If HTML tag exist in the simple input field, save returns 500 error

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1038]
This is and old issue, but i think that now then blogs import is implemented it should be fixed as now post info is imported as it is in xml.

**Comment by Adomavicius** [comment]
After a discussion with @smikulenas the decided fields to accept HTML are the following:
* Page Name in Page Properties
* Page Name in Edit Seo
* Post Title in Blog
* Page Title in Master Pages
* Page Title in Translate Page

Several of these fields were made HTML compliant during the development of #1200.

**Comment by Audrunas** [comment]
Fix is available in 1.11.0

**Comment by KarolisBab** [comment]
500 error still happens here:
Edit SEO->Meta Keywords
Edit SEO->Meta Description
Site settings->Tags->Add new tag
Site settings->Media Manager->Images->New Folder Name
Site settings->Media Manager->Files->New Folder Name
Site settings->Widgets->Register+->Widget Path
Site settings->Users->Add new User

HTML is accepted, but it should not be (as far as I can tell) here:
Edit SEO->Meta Title

**Comment by gerbenis** [comment]
It is OK to accept HTML in Edit SEO->Meta Title as we encode it. As for 500 error, validation message won't be implemented.
