### ISSUE TITLE
Search for pages with draft content does not work

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1308]
![image](https://cloud.githubusercontent.com/assets/2108569/9925766/e147c196-5d17-11e5-87ef-8741dc251861.png)

**Comment by JuliusSenkus** [comment]
Search works incorrectly when draft widget is inserted, how to reproduce:
1. Insert draft widget.
2. Remove it from content.
3. Then search content containing unpublished content.

**Comment by Audrunas** [comment]
Fix is available from 1.11.0-beta0

**Comment by mantas-janulionis** [comment]
Fix is available from 1.11.0-beta05+

**Comment by daivabrazukaite** [comment]
As i understand search by unpublished content should return items, that contains any type of draft content, but now:
1) Pages: only those pages, that has at least one published with draft content are returned (any type). So, if there are just drafts without published yet versions, page won't be returned as filtering result.
2) Blogs: only those blogs, that contains blog content as draft without published yet version are returned. And if blog content is published with draft (issue#2.1) OR there is at last one other type draft  content (issue#2.2) added - blog won't be returned

P.s.: I think this functionality was missed and not tested at all :(

**Comment by mantas-janulionis** [comment]
Fix is available in 1.11.0-beta11+

**Comment by daivabrazukaite** [comment]
Filtering in pages list works ok (item#1), but in blogs list (i.e. **Site settings -> Blogs**) - still not everything is ok:
2.1) Blog post is not returned if it has blog/html/markdown/plain text published with draft content
Steps: create blog and save it as published -> open blog content for edit and save it as draft -> filter in Blogs list: record won't be returned
2.2) Blog post is returned as containing unpublished content if it had assigned draft/published with draft widget but now it is removed (i.e. initial reason why bug was created)
Steps: create blog with published blog content -> add new content -> widget -> choose any widget with is draft or published with draft -> remove widget content from blog -> filter in Blogs list: record still be returned:

**Comment by smikulenas** [comment]
Fixed in version 1.11.0-beta13+

**Comment by KarolisBab** [comment]
this is still not fixed:
2.2) Blog post is returned as containing unpublished content if it had assigned draft/published with draft widget but now it is removed (i.e. initial reason why bug was created)
Steps: create blog with published blog content -> add new content -> widget -> choose any widget with is draft or published with draft -> remove widget content from blog -> filter in Blogs list: record still be returned.
Reproduced with the same steps on beta13 build.

**Comment by smikulenas** [comment]
Please double check on 1.11.0-beta14
