### ISSUE TITLE
Widget: incorrect boolean value is presented after language change

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1342]
Next issues exist with boolean option values:
- Incorrect value is presented for edit (always True) in already saved languages; incorrect default value is presented trying to save it in new language (always True)
- No value is displayed in view mode after language change

Scenario: Add/edit widget -> options -> add boolean option and set it value to True for Default language -> change language to some other (lang1) and set value to False -> Save widget -> open widget for edit -> options -> 'No' will be presented as default value in default lang (ok). Change language to lang1: no value will be visible as default one. Open option for edit: checkbox is ON. 

P.s.: correct default and translated values are saved in db

**Comment by mantas-janulionis** [comment]
Fix is available in version 1.11.0-beta04+

**Comment by daivabrazukaite** [comment]
It is still not ok with boolean value presentation in widget options grid: now always last chosen value is displayed after changing language.
Steps: add option with type 'boolean' for default language -> set its value to True -> change language to for example Eng -> edit and set as False -> open Default or choose some other language: No (i.e. false) value will be displayed, even it should be Yes (i.e. True), as it is set for Default lang (issue is just with presentation as correct values are saved in db).

**Comment by mantas-janulionis** [comment]
Fix is available in 1.11.0-beta08+
