### ISSUE TITLE
Widget options: please double check image folder value correctness

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1412]
For option with type 'image folder' now it is saved folder name (checked in db) while previously i guess it was saved id (checked on demo.bettercms.com using CmsWidgetOption functionality) and maybe this is the reason why next problems occur:
1) If option with type 'image folder' is chosen  to be displayed using CmsWidgetOption:{imageFolderOptionName}, no value is displayed
2) ImagesGalleryWidget always displays Root folder child folders instead of chosen folder sub-folders.
3) AlbumWidget always displays Root folder images instead of chosen folder images

I do not think that current approach to save image folder name as ContentOptions.defaultValue/ ContentOptionTranslations.value is correct as more than one folder can have same name (it is not very logical, but...)

**Comment by mantas-janulionis** [comment]
Fix is available in 1.11.0-beta08+

**Comment by daivabrazukaite** [comment]
1) ok, now correct assigned folder ID is displayed
2 - 3 still the same and always root folders/images are provided using gallery widgets - these widget are used in http://demo.bettercms.com/ page, so maybe some code update for these widgets is needed? Please check.

**Comment by mantas-janulionis** [comment]
Fixed in version 1.11.0-beta11+
