### ISSUE TITLE
Widget in widget options: original value should be used for all languages that has "use default" = Yes

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1430]
Create widget1 with at least one option (for case#1 there is no need for translations; for case#2 one translation is needed), make its value displayed in html -> create widget2 -> add widget1 into widget2 html -> add widget2 as some page content -> open widget2 for edit -> open child widget options modal (right click on widget1 -> choose "widget  options"):
1) language1 <> Default  has "use default" = NO and new value assigned as child widget option value: value will be available only for this specific language and all other languages will have no value.
Steps: Choose language1 (! use some other than Default, for example LT) -> open option for edit, set "use default" = NO and enter new value -> close modal -> save and publish widget2 -> try changing page languages: value will be available only for language1 and for all other languages - there will be no value. 
2) Default language has "use default" = NO with some new value assigned in child widget options AND language1 has some translation assigned as original widget (widget1) value: new child widget value assigned to Default language will be displayed for all languages, including language1
Steps: choose Default language -> open option for edit, set "use default" = NO and enter new value -> close modal (i.e. language1 still has "use default" = Yes) -> save and publish widget2 -> try changing page languages: new value will be visible for all languages.

Should be: in both upper described cases, original widget1 assigned value for languageX should be presented if it is not specified other way in child widget modal.

**Comment by mantas-janulionis** [comment]
Fixed in version 1.11.0-beta11+

**Comment by daivabrazukaite** [comment]
Now it is ok if only default language value is changed in child widget options, but all other cases are still not ok. Use same scenario: there is widget1 with option and some value assigned to it (no translations) and this option displayed in widget content -> widget1 is inserted into widget2 and widget2 is added as some page content:
1) Language1 (language1 <> Default lnaguage) value is changed in child widget options: only language1 and default language will contain values in page
Steps: Open widget2 for edit -> open child widget options (double click on widget1) -> choose for example ENG language -> set "Use default" = NO and enter some new value -> close child widget options -> save and publish widget2 -> try changing page languages: Default - widget1 default language assigned value will be displayed (ok), ENG - widget2 child value assigned for ENG (ok), LT - no value is displayed (not ok). P.s.: if you open child widget options, correct values will be visible there.
2) Default language and Language1 values are changed in child widget options: widget2 assigned value for default language is displayed for all other languages except language1 in page, but widget1 values in child widget options modal

**Comment by mantas-janulionis** [comment]
Fixed in version 1.11.0-beta13+

**Comment by daivabrazukaite** [comment]
As agreed actual result should not be as described in this task, separate task #1478 was created based on scenarios tested there
