### ISSUE TITLE
Options: no value should be defaulted into option name field

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1433]
Open for example page properties -> options tab -> add new -> choose "image URL" type -> leave name field empty and choose any image in value field: after image selection modal will be closed, URL will be inserted into both, name and value, fields. Same for "images Folder" type.
Should be: name value should not be filled in if it is null after folder/image is selected.

**Comment by mantas-janulionis** [comment]
Fix is available in 1.11.0-beta11+

**Comment by KarolisBab** [comment]
![images folder](https://cloud.githubusercontent.com/assets/15941028/11436745/248ef194-94f0-11e5-9ebb-0b13cd5f2b6b.PNG)
Issue is still present with "Images Folder"
